FROM node:16-alpine

# create destination directory
RUN mkdir -p /learn-nuxt
WORKDIR /learn-nuxt

# # update and install dependency
# RUN apk update && apk upgrade
# RUN apk add git

# copy the app, note .dockerignore
COPY . /learn-nuxt/
RUN npm install forever@latest -g

RUN cd backend

RUN npm install && npm run build

# start the app
CMD [ "npm", "run" , "start" ]